// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlQ6nEXvCV6rBwWZbMaRBkW-GH7B1baS4',
    appId: '1:696893837141:android:2199754a1d7f85662569dc',
    messagingSenderId: '696893837141',
    projectId: 'borrow-app-12345',
    storageBucket: 'borrow-app-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWt1wSHnUw0NaRPjBkra63Dqq0gV9coA4',
    appId: '1:696893837141:ios:53bc329cbbe40a732569dc',
    messagingSenderId: '696893837141',
    projectId: 'borrow-app-12345',
    storageBucket: 'borrow-app-12345.firebasestorage.app',
    iosBundleId: 'com.example.borrowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWt1wSHnUw0NaRPjBkra63Dqq0gV9coA4',
    appId: '1:696893837141:ios:53bc329cbbe40a732569dc',
    messagingSenderId: '696893837141',
    projectId: 'borrow-app-12345',
    storageBucket: 'borrow-app-12345.firebasestorage.app',
    iosBundleId: 'com.example.borrowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3mDFhVs12OvfPECigLNzpYrlN_n6kVdY',
    appId: '1:696893837141:web:60a2330dee19f4f52569dc',
    messagingSenderId: '696893837141',
    projectId: 'borrow-app-12345',
    authDomain: 'borrow-app-12345.firebaseapp.com',
    storageBucket: 'borrow-app-12345.firebasestorage.app',
    measurementId: 'G-VR90ZQ124F',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3mDFhVs12OvfPECigLNzpYrlN_n6kVdY',
    appId: '1:696893837141:web:60a2330dee19f4f52569dc',
    messagingSenderId: '696893837141',
    projectId: 'borrow-app-12345',
    authDomain: 'borrow-app-12345.firebaseapp.com',
    storageBucket: 'borrow-app-12345.firebasestorage.app',
    measurementId: 'G-VR90ZQ124F',
  );

}